// Test IDs for the projects feature.

export const PROJECTS = {
  page: 'projects-page',
  searchInput: 'projects-search-input',
  statusFilter: 'projects-status-filter',
  chartViewBtn: 'projects-chart-view-btn',
  listViewBtn: 'projects-list-view-btn',
  newProjectBtn: 'projects-new-project-btn',
  metricActive: 'projects-metric-active',
  metricRework: 'projects-metric-rework',
  metricDueWeek: 'projects-metric-due-week',
  metricDeliverables: 'projects-metric-deliverables',
  columnPlanning: 'projects-column-planning',
  columnActive: 'projects-column-active',
  columnRework: 'projects-column-rework',
  columnCompleted: 'projects-column-completed',
  cardPrefix: 'project-card',
  listRowPrefix: 'project-list-row',
  emptyState: 'projects-empty-state',
  loadingState: 'projects-loading-state',
  // Modal
  modal: 'create-project-modal',
  modalClose: 'create-project-modal-close',
  modalCancel: 'create-project-modal-cancel',
  modalSubmit: 'create-project-modal-submit',
  fieldName: 'create-project-field-name',
  fieldClient: 'create-project-field-client',
  fieldStart: 'create-project-field-start',
  fieldEnd: 'create-project-field-end',
  fieldPoc: 'create-project-field-poc',
  addDeliverableBtn: 'create-project-add-deliverable-btn',
  deliverableRowPrefix: 'create-project-deliverable-row',
  deliverableRemovePrefix: 'create-project-deliverable-remove',
};
