// Test IDs for the work sheet feature.

export const WORKSHEET = {
  roleSwitcher: 'worksheet-role-switcher',
  searchInput: 'worksheet-search-input',
  statusFilter: 'worksheet-status-filter',
  typeFilter: 'worksheet-type-filter',
  categoryFilter: 'worksheet-category-filter',
  monthFilter: 'worksheet-month-filter',
  clearFiltersBtn: 'worksheet-clear-filters-btn',
  addRowBtn: 'worksheet-add-row-btn',
  table: 'worksheet-table',
  emptyState: 'worksheet-empty-state',
  loadingState: 'worksheet-loading-state',
  dateInput: 'worksheet-date-input',
  deliverableInput: 'worksheet-deliverable-input',
  typeSelect: 'worksheet-type-select',
  categorySelect: 'worksheet-category-select',
  versionInput: 'worksheet-version-input',
  timeInput: 'worksheet-time-input',
  creatorSelect: 'worksheet-creator-select',
  reviewerSelect: 'worksheet-reviewer-select',
  remarksInput: 'worksheet-remarks-input',
  statusSelect: 'worksheet-status-select',
  deleteRowBtn: 'worksheet-delete-row-btn',
  myRowsCount: 'worksheet-my-rows-count',
  deliverableLinkInput: 'worksheet-deliverable-link-input',
  closeDeliverableBtn: 'worksheet-close-deliverable-btn',
};
